Try a full shell script
Signed-off-by: jdarwood007 <unmonitored+github@sleepycode.com>

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -13,8 +13,30 @@ jobs:
     - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
     - name: Build
       run: |
-        wget https://raw.githubusercontent.com/jdarwood007/buildMod/570dc6092cff7a5ecdc517af87b8154a4c69fe15/build_mod_package.php -O ${{ runner.temp }}/build_mod_package.php
-        php ${{ runner.temp }}/build_mod_package.php --src=. --dst=${{ runner.temp }}
+        # Get the version name.
+        NAME=$(sed -nE 's/<name>([^<]+)<\/name>/\1/p' package-info.xml | awk '{$1=$1};1')
+        NAME=`echo $NAME | sed -e "s/ /-/g"`
+        
+        # Get the version and clean it up.
+        VERSION=$(sed -nE 's/<version>([^<]+)<\/version>/\1/p' package-info.xml | awk '{$1=$1};1' | awk '{for(i=1;i<=NF;i++){ $i=toupper(substr($i,1,1)) substr($i,2) }}1')
+        VERSION=`echo $VERSION | sed -e "s/ /-/g"`
+        VERSION=`echo $VERSION | sed -e "s/Rc/RC/g"`
+        
+        if [ -z "${VERSION}" ]; then echo "Version is missing"; exit 1; fi
+        if [ -z "${NAME}" ]; then echo "Name is missing"; exit 1; fi
+        
+        BASE_FILE="${NAME}_${VERSION}"
+        
+        # Tar with gz
+        if [ "$(uname)" == "Darwin" ]; then
+            tar --no-xattrs --no-acls --no-mac-metadata --no-fflags --exclude='.git' --exclude='screenshots' --exclude='vendor' --exclude='.*' --exclude='composer.*' -czf ${{ runner.temp }}/$BASE_FILE.tgz *
+        else
+            tar --no-xattrs --no-acls--exclude='.git' --exclude='screenshots' --exclude='vendor' --exclude='.*' --exclude='composer.*' -czf ${{ runner.temp }}/$BASE_FILE.tgz *
+        fi
+        
+        # Zip
+        zip -x ".git" "screenshots/*" "vendor/*"  ".*/" "composer.*"  -1 ${{ runner.temp }}/$BASE_FILE.zip -r *
+
         cd ${{ runner.temp }}
         echo "TGZ_FILE=`ls *.tgz`" >> $GITHUB_ENV
         echo "ZIP_FILE=`ls *.zip`" >> $GITHUB_ENV
